### ISSUE TITLE
Autocomplete method not working

### ISSUE THREAD

**Issue by killatsignlife** [vectier/tslombok#4]
When I write 'get' or 'set' in VS Code, it doesn't autocomplete, and it doesn't identify getters and setters generated by TSLombok. I want to know if this is a problem with VS Code on my machine or if TSLombok is not integrated with VS Code's autocomplete.

![image](https://github.com/vectier/tslombok/assets/60820935/e64853fd-e3a7-4414-954a-a04db5970723)

**Comment by riflowth** [comment]
@LeiteSS Sorry for very late reply. Are you running a `npx tslombok` while developing? As mentioned in https://github.com/vectier/tslombok#getting-started

We are plan to improve TSLombok to run without `npx tslombok` command.

**Comment by killatsignlife** [comment]
Hi @riflowth, thank you for the response, and no, I didn't use npx tslombok; I hadn't seen that part in the documentation. 

I'm sorry for the inconvenience, thanks again!
